# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fire5.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets
from PyQt5.QtGui import QIcon, QPixmap


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1084, 723)
        MainWindow.setStyleSheet("border: 0;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("\n"
                                         "background:#1e5da6;\n"
                                         "border: 0;\n"
                                         "padding: 0;\n"
                                         "margin: 0;\n"
                                         "")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.camera = QtWidgets.QLabel(self.centralwidget)
        self.camera.setMinimumSize(QtCore.QSize(800, 660))
        self.camera.setMaximumSize(QtCore.QSize(1090, 900))
        self.camera.setStyleSheet("background: rgba(255,255,255,0.7);\n"
                                  "border: 0;\n"
                                  "padding: 0;\n"
                                  "margin: 0;\n"
                                  "font-size: 20px;")
        self.camera.setAlignment(QtCore.Qt.AlignCenter)  # 文字居中
        self.camera.setObjectName("camera")
        self.horizontalLayout.addWidget(self.camera)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(260, 0))
        self.frame.setMaximumSize(QtCore.QSize(300, 16777215))
        self.frame.setStyleSheet("\n"
                                 "border: 0;\n"
                                 "padding: 0;\n"
                                 "margin: 0;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.timedisplay = QtWidgets.QLabel(self.frame)
        self.timedisplay.setMinimumSize(QtCore.QSize(190, 0))
        self.timedisplay.setMaximumSize(QtCore.QSize(300, 35))
        self.timedisplay.setStyleSheet("color:#FFFFFF;\n"
                                       "padding: 5px;\n"
                                       "font-size: 15px;\n"
                                       "margin-bottom: 5px;\n"
                                       "border: 1px solid #99CCFF;\n"
                                       "border-radius: 10px\n"
                                       "")
        self.timedisplay.setAlignment(QtCore.Qt.AlignCenter)  # 文字居中
        self.timedisplay.setObjectName("timedisplay")
        self.verticalLayout_2.addWidget(self.timedisplay)
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setMaximumSize(QtCore.QSize(300, 35))
        self.label_3.setStyleSheet("font-size: 25px;\n"
                                   "color:#FFFFFF;\n"
                                   "padding: 5px;")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)  # 文字居中
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        spacerItem = QtWidgets.QSpacerItem(17, 37, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.email_label_2 = QtWidgets.QLabel(self.frame)
        self.email_label_2.setMaximumSize(QtCore.QSize(60, 35))
        self.email_label_2.setStyleSheet("color:#FFFFFF;\n"
                                       "padding: 5px;\n"
                                       "font-size: 15px;\n"
                                       "margin-bottom: 5px;\n"
                                       "border: 1px solid #99CCFF;")
        self.email_label_2.setObjectName("email_label_2")
        self.horizontalLayout_8.addWidget(self.email_label_2)
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setStyleSheet("color:#FFFFFF;\n"
                                    "padding: 5px;\n"
                                    "font-size: 15px;\n"
                                    "margin-bottom: 5px;\n"
                                    "border: 1px solid #99CCFF;")
        self.lineEdit.setObjectName("lineEdit")

        self.horizontalLayout_8.addWidget(self.lineEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)


        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.model_label = QtWidgets.QLabel(self.frame)
        self.model_label.setMaximumSize(QtCore.QSize(60, 35))
        self.model_label.setStyleSheet("color:#FFFFFF;\n"
                                       "padding: 5px;\n"
                                       "font-size: 15px;\n"
                                       "margin-bottom: 5px;\n"
                                       "border: 1px solid #99CCFF;")
        self.model_label.setObjectName("model_label")
        self.horizontalLayout_4.addWidget(self.model_label)
        self.comboBox_2 = QtWidgets.QComboBox(self.frame)
        self.comboBox_2.setStyleSheet("color:#FFFFFF;\n"
                                      "padding: 5px;\n"
                                      "font-size: 15px;\n"
                                      "margin-bottom: 5px;\n"
                                      "border: 1px solid #99CCFF;\n"
                                      "")
        self.comboBox_2.setObjectName("comboBox_2")
        self.horizontalLayout_4.addWidget(self.comboBox_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)

        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.input_label = QtWidgets.QLabel(self.frame)
        self.input_label.setMaximumSize(QtCore.QSize(60, 35))
        self.input_label.setStyleSheet("color:#FFFFFF;\n"
                                       "padding: 5px;\n"
                                       "font-size: 15px;\n"
                                       "margin-bottom: 5px;\n"
                                       "border: 1px solid #99CCFF;")
        self.input_label.setObjectName("input_label")
        self.horizontalLayout_5.addWidget(self.input_label)
        self.picture = QtWidgets.QPushButton(self.frame)
        self.picture.setMaximumSize(QtCore.QSize(200, 35))
        self.picture.setStyleSheet("\n"
                                   "color:#FFFFFF;\n"
                                   "padding: 5px;\n"
                                   "font-size: 13px;\n"
                                   "margin-bottom: 5px;\n"
                                   "border: 1px solid #99CCFF;\n"
                                   "border-radius: 10px")
        self.picture.setIcon(QIcon('./pyqt5/components/upload.png'))
        self.picture.setObjectName("picture")
        self.horizontalLayout_5.addWidget(self.picture)
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton.setMaximumSize(QtCore.QSize(200, 35))
        self.pushButton.setStyleSheet("\n"
                                      "color:#FFFFFF;\n"
                                      "padding: 5px;\n"
                                      "font-size: 13px;\n"
                                      "margin-bottom: 5px;\n"
                                      "border: 1px solid #99CCFF;\n"
                                      "border-radius: 10px")
        # 加载图标文件
        self.pushButton.setIcon(QIcon('./pyqt5/components/camera.png'))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_5.addWidget(self.pushButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.output_label = QtWidgets.QLabel(self.frame)
        self.output_label.setMaximumSize(QtCore.QSize(60, 35))
        self.output_label.setStyleSheet("color:#FFFFFF;\n"
                                        "padding: 5px;\n"
                                        "font-size: 15px;\n"
                                        "margin-bottom: 5px;\n"
                                        "border: 1px solid #99CCFF;")
        self.output_label.setObjectName("output_label")
        self.horizontalLayout_6.addWidget(self.output_label)
        self.look = QtWidgets.QPushButton(self.frame)
        self.look.setMinimumSize(QtCore.QSize(0, 0))
        self.look.setMaximumSize(QtCore.QSize(200, 35))
        self.look.setStyleSheet("\n"
                                "color:#FFFFFF;\n"
                                "font-size: 15px;\n"
                                "padding: 5px;\n"
                                "margin-bottom: 5px;\n"
                                "border: 1px solid #99CCFF;\n"
                                "border-radius: 10px")
        self.look.setIcon(QIcon('./pyqt5/components/check.png'))
        self.look.setObjectName("look")
        self.horizontalLayout_6.addWidget(self.look)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        spacerItem1 = QtWidgets.QSpacerItem(17, 37, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setMaximumSize(QtCore.QSize(200, 30))
        self.label_8.setStyleSheet("color:#FFFFFF;\n"
                                   "font-size: 20px;\n"
                                   "padding: 5px;\n"
                                   "border: 1px solid #2c80ee;\n"
                                   "border-radius: 10px")
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_7.addWidget(self.label_8)
        self.clear_all = QtWidgets.QPushButton(self.frame)
        self.clear_all.setMinimumSize(QtCore.QSize(50, 0))
        # 加载图标文件
        self.clear_all.setIcon(QIcon('./pyqt5/components/delete.png'))
        self.clear_all.setObjectName("clear_all")
        self.horizontalLayout_7.addWidget(self.clear_all)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.result_output = QtWidgets.QTextEdit(self.frame)
        self.result_output.setMinimumSize(QtCore.QSize(200, 0))
        self.result_output.setMaximumSize(QtCore.QSize(500, 20000))
        self.result_output.setStyleSheet("background:#6494ce;\n"
                                         "color:#FFFFFF;")
        self.result_output.setObjectName("result_output")
        self.horizontalLayout_2.addWidget(self.result_output)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1084, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "火焰识别预警"))
        self.camera.setText(_translate("MainWindow", "显示区域"))
        self.timedisplay.setText(_translate("MainWindow", "时间"))
        self.label_3.setText(_translate("MainWindow", "火焰烟雾识别"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "请输入邮箱（可选）"))
        self.email_label_2.setText(_translate("MainWindow", "邮箱："))
        self.model_label.setText(_translate("MainWindow", "模型："))
        self.input_label.setText(_translate("MainWindow", "输入："))
        self.picture.setText(_translate("MainWindow", "本地上传"))
        self.pushButton.setText(_translate("MainWindow", "实时获取"))
        self.output_label.setText(_translate("MainWindow", "输出："))
        self.look.setText(_translate("MainWindow", "查看图片"))
        self.label_8.setText(_translate("MainWindow", "检测结果打印："))
        self.result_output.setHtml(_translate("MainWindow",
                                              "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                              "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                              "p, li { white-space: pre-wrap; }\n"
                                              "</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
                                              "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
